version: 2.1
jobs:
  test-source:
    description: 'ESLint source files'
    docker:
      - image: node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint TS / JS
          command: |
            yarn install
            yarn lint
      - run:
          name: Test TS
          command: |
            yarn build
            yarn test
  test-docker:
    parameters:
      dir:
        type: string
        default: ''
    description: 'lint-dockerfile << parameters.container-image >>'
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Dockerfile
          command: |
            dir=<< parameters.dir >>
            if [ "$dir" = "" ]; then dir="." ; fi
            docker run --rm -i hadolint/hadolint /bin/hadolint - < $dir/Dockerfile
      - run:
          name: Build images
          command: |
            dir=<< parameters.dir >>
            if [ "$dir" = "" ]; then dir="." ; fi
            docker build -t test:latest $dir
workflows:
  main:
    jobs:
      - test-source
      - test-docker
