// Generated by https://quicktype.io

export interface ImgurResponse {
	data: Datum[];
	success: boolean;
	status: number;
}

export interface Datum {
	id: string;
	title: string;
	description: null | string;
	datetime: number;
	cover?: string;
	cover_width?: number;
	cover_height?: number;
	account_url: string;
	account_id: number;
	privacy?: Privacy;
	layout?: Layout;
	views: number;
	link: string;
	ups: number;
	downs: number;
	points: number;
	score: number;
	is_album: boolean;
	vote: null;
	favorite: boolean;
	nsfw: boolean;
	section: Section;
	comment_count: number;
	favorite_count: number;
	topic: Topic;
	topic_id: number;
	images_count?: number;
	in_gallery: boolean;
	is_ad: boolean;
	tags: Tag[];
	ad_type: number;
	ad_url: string;
	in_most_viral: boolean;
	include_album_ads?: boolean;
	images?: Image[];
	ad_config: AdConfig;
	type?: Type;
	animated?: boolean;
	width?: number;
	height?: number;
	size?: number;
	bandwidth?: number;
	has_sound?: boolean;
	edited?: number;
	mp4?: string;
	gifv?: string;
	hls?: string;
	mp4_size?: number;
	looping?: boolean;
	processing?: Processing;
}

export interface AdConfig {
	safeFlags: SafeFlag[];
	highRiskFlags: any[];
	unsafeFlags: UnsafeFlag[];
	wallUnsafeFlags: any[];
	showsAds: boolean;
}

export enum SafeFlag {
	Album = 'album',
	Gallery = 'gallery',
	InGallery = 'in_gallery',
	OnsfwModSafe = 'onsfw_mod_safe',
	PageLoad = 'page_load',
	SixthModSafe = 'sixth_mod_safe',
}

export enum UnsafeFlag {
	SixthModUnsafe = 'sixth_mod_unsafe',
	Spam = 'spam',
	Under10 = 'under_10',
}

export interface Image {
	id: string;
	title: null | string;
	description: null | string;
	datetime: number;
	type: Type;
	animated: boolean;
	width: number;
	height: number;
	size: number;
	views: number;
	bandwidth: number;
	vote: null;
	favorite: boolean;
	nsfw: null;
	section: null;
	account_url: null;
	account_id: null;
	is_ad: boolean;
	in_most_viral: boolean;
	has_sound: boolean;
	tags: any[];
	ad_type: number;
	ad_url: string;
	edited: string;
	in_gallery: boolean;
	link: string;
	comment_count: null;
	favorite_count: null;
	ups: null;
	downs: null;
	points: null;
	score: null;
	mp4?: string;
	gifv?: string;
	hls?: string;
	mp4_size?: number;
	looping?: boolean;
	processing?: Processing;
}

export interface Processing {
	status: Status;
}

export enum Status {
	Completed = 'completed',
}

export enum Type {
	ImageGIF = 'image/gif',
	ImageJPEG = 'image/jpeg',
	ImagePNG = 'image/png',
	VideoMp4 = 'video/mp4',
}

export enum Layout {
	Blog = 'blog',
}

export enum Privacy {
	Hidden = 'hidden',
	Public = 'public',
}

export enum Section {
	Empty = '',
	SupermodelCats = 'SupermodelCats',
}

export interface Tag {
	name: string;
	display_name: string;
	followers: number;
	total_items: number;
	following: boolean;
	is_whitelisted: boolean;
	background_hash: string;
	thumbnail_hash: null;
	accent: null | string;
	background_is_animated: boolean;
	thumbnail_is_animated: boolean;
	is_promoted: boolean;
	description: string;
	logo_hash: null;
	logo_destination_url: null;
	description_annotations: DescriptionAnnotations;
}

export interface DescriptionAnnotations {}

export enum Topic {
	NoTopic = 'No Topic',
}
